### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by fakepilot** [Aeoll/ae_SVG#5]
Hello, already loving this plugin! 
Now that Houdini is switching to Python 3, is it a lot of work switching?

**Comment by Aeoll** [comment]
It don't think it will need many changes, but I won't be working on a port until we move over to Python3 at work - which I imagine will be when Houdini 19 and it becomes the default. At that point I'll port along with the rest of Aelib

**Comment by spezialspezial** [comment]
Just testing it on Python 3. After changing the RGBtoHex function to it writes out svg files. Upside down so far but hey.
`
def RGBtoHex(rgbarray):
    return "#" + "".join([f'{max(min(int(c*255),255),0):0>2x}' for c in rgbarray])
`

**Comment by alt-st** [comment]
Hello! I'm Testing svg Export on houdini 18.0.566 and getting the following error when exporting:
```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
   File "opdef:/ae::Sop/SVG_Export::3?PythonModule", line 155, in exportSVG
   File "opdef:/ae::Sop/SVG_Export::3?PythonModule", line 34, in RGBtoHex
AttributeError: 'str' object has no attribute 'hex'
```   
Is the problem with the version of houdini (the version of python built into it) or something else? What can be done besides changing the version of houdini to make the SVG export work?
